openapi: 3.1.0
info:
  title: todo
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /items:
    get:
      summary: Get TODO items
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TodoItem'
              examples: {}
      operationId: v1.getItems
      description: Return a list of todo items
    post:
      summary: Add new TODO
      operationId: v1.postItem
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
      description: Adds new todo item
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
  '/items/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: todo item unique ID
    patch:
      summary: Update TODO item
      operationId: v1.patchItems
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                done:
                  type: string
components:
  schemas:
    TodoItem:
      title: TodoItem
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          x-faker: lorem.sentence
        description:
          type:
            - string
            - 'null'
        done:
          type: boolean
      required:
        - id
        - title
        - description
        - done
      examples:
        - id: e4771e74-aca2-40f9-9fc6-3f4710aee33a
          title: Shopping
          description: don't forget to buy toothpaste
          done: false
        - id: 484e417f-2a35-45e4-8ad8-58d93f91b2f4
          title: workout
          description: more push ups today
          done: false
        - id: e4771e74-aca2-40f9-9fc6-3f4710aee33a
          title: dentist
          description: null
          done: false
        - id: e4771e74-aca2-40f9-9fc6-3f4710aee33a
          title: Spend 2 hrs on blog article
          description: null
          done: false
      description: Todo Item
